// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHk3yo2igYDNrZ2qBe79ZYuKeLmq7Vb8',
    appId: '1:440642972972:web:f2ec810921e98ed1d9d089',
    messagingSenderId: '440642972972',
    projectId: 'grade-12-app-f768e',
    authDomain: 'grade-12-app-f768e.firebaseapp.com',
    storageBucket: 'grade-12-app-f768e.firebasestorage.app',
    measurementId: 'G-L9KWCRFWZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhXGtG41gpBEG8dXj-BMT_jZzKJUBFV0',
    appId: '1:440642972972:android:57ea7e7c1fad27f2d9d089',
    messagingSenderId: '440642972972',
    projectId: 'grade-12-app-f768e',
    storageBucket: 'grade-12-app-f768e.firebasestorage.app',
  );
}
